#!/usr/bin/env bash


path="~/Artifacts"
name="Artifacts"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$name" -c "$path"
  exit 0
fi

if ! tmux has-session -t="$name" 2>/dev/null; then
  tmux new-session -ds "$name" -c "$path" -e PROJECT_DIR="$path"
fi

if [[ -z $TMUX ]]; then
  tmux attach -t "$name"
else
  tmux switch-client -t "$name"
fi

exit 1

