#!/usr/bin/env bash

echo "Please Select A Search Type"
echo "  f: Find project directory"
echo "  s: Find ssh connection"

read -rn 1 TMUX_FindType

#Find Directory
if [[ "$TMUX_FindType" = "f" ]]; then

  if [[ $# -eq 1 ]]; then
    selected=$1
  else
    selected=$(find ~/Code -mindepth 1 -maxdepth 1 -type d | fzf --tmux)
  fi

  if [[ -z $selected ]]; then
    exit 0
  fi

  selected_name=$(basename "$selected" | tr . _)
  tmux_running=$(pgrep tmux)

  if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
  fi

  if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected" -e PROJECT_DIR="$selected"
  fi

  if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
  else
    tmux switch-client -t "$selected_name"
  fi
fi

# Find SSH Session
if [[ "$TMUX_FindType" = "s" ]]; then
  selected=$(perl ~/.local/scripts/ssh_hosts.pl ~/.ssh/config | fzf)
  if [[ -z $selected ]]; then
    exit 0
  fi

  selected_name=$(basename "$selected" | tr . _)
  tmux_running=$(pgrep tmux)

  if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
  fi

  if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
  fi

  if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
  else
    tmux switch-client -t "$selected_name"
  fi
fi
